version: '3.1'
services:
  wordpress:
    image: wordpress:php8.0
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      UPLOAD_LIMIT: 64M
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins
      - ./themes:/var/www/html/wp-content/themes
      - wordpress:/var/www/html
      - ./php.ini-development:/usr/local/etc/php/php.ini-development
      - ./php.ini-production:/usr/local/etc/php/php.ini-production
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

      
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      UPLOAD_LIMIT: 64M
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  wordpress:
  db: