services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: DIE-wordpress-mysql
    tty: true
    ports:
      - "4208:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - DIE-wordpress-net
    env_file:
      - .env
  wordpress:
    image: wordpress:latest
    restart: always
    container_name: DIE-wordpress
    ports:
      - "4282:80"
    volumes:
      - "./wp-content:/var/www/html/wp-content"
      - "./PS:/var/www/html/wp-content/plugins/PS"
    environment:
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_HOST: DIE-wordpress-mysql
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', true);
        define('SCRIPT_DEBUG', true);
        define('SAVEQUERIES', true);
        define('FORCE_SSL_ADMIN', false); // Desactiva la redirección SSL en el panel de administración
        define('WP_HOME', 'http://localhost:4282'); // Establece el dominio principal
        define('WP_SITEURL', 'http://localhost:4282'); // Establece la URL del sitio

    depends_on:
      - mysql
    networks:
      - DIE-wordpress-net
    env_file:
      - .env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: DIE-phpmyadmin
    ports:
      - "4283:80"
    environment:
      PMA_HOST: DIE-wordpress-mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
    networks:
      - DIE-wordpress-net
    env_file:
      - .env
networks:
  DIE-wordpress-net:
    driver: bridge
volumes:
  mysql-data:
